org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC
org.gradle.parallel=false
org.gradle.caching=true
# org.gradle.configuration-cache=true

android.enableAppCompileTimeRClass=true
android.enableBuildConfigAsBytecode=true
android.useAndroidX=true
# Improve build performance by enabling R8 parallelism.
android.r8.maxWorkers=1

kotlin.code.style=official
# Proxy configuration
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1
